### ISSUE TITLE
Disappearing Events?

### ISSUE THREAD

**Issue by CyberStrike** [CyberStrike/soflo#15]
Just happened to me on production with event/4 when I set the start time to 8:30pm

**Comment by CyberStrike** [comment]
Reproduced +1

**Comment by CyberStrike** [comment]
Any event with a start between 8:00 - 11:59 pm on a Saturday disappears.

**Comment by eddroid** [comment]
Feature-not-a-bug?

**Comment by CyberStrike** [comment]
@eddroid :laughing: 

I have a feeling it has to do with this line.
https://github.com/CyberStrike/soflo/blob/master/app/controllers/events_controller.rb#L10
```ruby
def index
    # @events = Event.all
    @events_by_week = Event.where(:start => @date.beginning_of_week..@date.end_of_week ).order(:start).group_by(&:startdate) || Event.this_week.order(:start).group_by(&:startdate)

    ## display variables

    @display_month = @date.year < Date.current.year ? @date.strftime("%B %Y") : @date.strftime("%B")

  end
```

**Comment by eddroid** [comment]
That makes sense. Your beginning/end of week boundaries are probably in GMT. We're in GMT-4.

If the day switches over at midnight GMT (Sunday morning), that's 8pm Eastern (Saturday night). So events after 8pm on Saturday roll over to "next week".

If `@date` is a `Time` or `DateTime` object, try converting it to a `Date` with `to_date` to chop off the time part.

*In the console*
\>\> `Time.now.beginning_of_week..Time.now.end_of_week`
=> 2015-03-23 00:00:00 -0400..2015-03-29 23:59:59 -0400

\>\> `Time.now.to_date.beginning_of_week..Time.now.to_date.end_of_week`
=> Mon, 23 Mar 2015..Sun, 29 Mar 2015

**Comment by CyberStrike** [comment]
It's a date object being grabbed from a param.

```ruby
def set_date
  @date = params[:date] ? Date.parse(params[:date]): Date.current
end
```

**Comment by CyberStrike** [comment]
Since it's being shoved ahead by 1 day. This should add that extra day to scope.

```ruby
 Event.where(:start => @date.yesterday..@date.end_of_week + 1.day)
```
